# Generated by Django 3.1.6 on 2021-02-28 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210208_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitydata',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='itemdata',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
