# Generated by Django 3.1.7 on 2021-05-30 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCApplication',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('confidential', 'Confidential')], default='confidential', max_length=255)),
                ('redirect_uris', models.JSONField()),
                ('default_redirect_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OIDCRefreshToken',
            fields=[
                ('jti', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expiry', models.DateTimeField(editable=False)),
                ('revoked', models.DateTimeField(blank=True, null=True)),
                ('claims', models.JSONField(editable=False)),
                ('application', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='authentication.oidcapplication')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OIDCIDToken',
            fields=[
                ('jti', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expiry', models.DateTimeField(editable=False)),
                ('revoked', models.DateTimeField(blank=True, null=True)),
                ('source_refresh_token', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='id_token', to='authentication.oidcrefreshtoken')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OIDCGrant',
            fields=[
                ('code', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('expiry', models.DateTimeField(editable=False)),
                ('redirect_uri', models.CharField(editable=False, max_length=255)),
                ('nonce', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('claims', models.JSONField(editable=False)),
                ('code_challenge', models.CharField(blank=True, editable=False, max_length=128, null=True)),
                ('code_challenge_method', models.CharField(blank=True, choices=[('s256', 'SHA256'), ('plain', 'Plain (insecure)')], editable=False, max_length=5, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('application', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='authentication.oidcapplication')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OIDCAccessToken',
            fields=[
                ('jti', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expiry', models.DateTimeField(editable=False)),
                ('revoked', models.DateTimeField(blank=True, null=True)),
                ('source_refresh_token', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to='authentication.oidcrefreshtoken')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
